FROM node:18.15.0-slim
MAINTAINER Aiden_FE <Aiden_FE@outlook.com>

# 声明构建环境 development/production
ARG NODE_ENV=production
# JWT验证密钥
ARG COMPASS_JWT_SECRET
# mysql连接地址
ARG COMPASS_MYSQL_DATABASE_URL
# redis host
ARG COMPASS_REDIS_HOST
# redis port
ARG COMPASS_REDIS_PORT=6379
# redis 连接密码
ARG COMPASS_REDIS_PASSWORD
# Recaptcha 密钥
ARG COMPASS_RECAPTCHA_SECRET
# 系统邮箱账号
ARG COMPASS_EMAIL_USER
# 系统邮箱密码
ARG COMPASS_EMAIL_PASSWORD

ENV NODE_ENV=${NODE_ENV}
ENV COMPASS_JWT_SECRET=${COMPASS_JWT_SECRET}
ENV COMPASS_MYSQL_DATABASE_URL=${COMPASS_MYSQL_DATABASE_URL}
ENV COMPASS_REDIS_HOST=${COMPASS_REDIS_HOST}
ENV COMPASS_REDIS_PORT=${COMPASS_REDIS_PORT}
ENV COMPASS_REDIS_PASSWORD=${COMPASS_REDIS_PASSWORD}
ENV COMPASS_RECAPTCHA_SECRET=${COMPASS_RECAPTCHA_SECRET}
ENV COMPASS_EMAIL_USER=${COMPASS_EMAIL_USER}
ENV COMPASS_EMAIL_PASSWORD=${COMPASS_EMAIL_PASSWORD}

ARG WORKDIR_DIR=/root/compass

WORKDIR ${WORKDIR_DIR}

COPY . ${WORKDIR_DIR}

EXPOSE 8080

CMD ["npm", "run", "start:prod"]
