version: "3"
networks:
  basic_service:
services:
  db:
    image: mysql:8.0.28
    restart: always
    networks:
      - basic_service
    container_name: basic_service_db
    environment:
      MYSQL_ROOT_PASSWORD: root123456 # root密码
      MYSQL_USER: aiden # 为db创建管理用户
      MYSQL_PASSWORD: aiden123456 # 设置管理用户的密码
      MYSQL_DATABASE: compass # 数据库名称
    command: --default-time-zone='+8:00' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./db:/var/lib/mysql" # 设置为实际挂载路径
    ports:
      - "3306:3306"
  redis:
    image: redis:6.2.6
    restart: always
    container_name: basic_service_redis
    ports:
      - "6379:6379"
    networks:
      - basic_service
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis-data:/data"
    command: redis-server /usr/local/etc/redis/redis.conf

# 另可直接架设供容器访问的主机网络
# docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 localNet
