export const NODE_ENV = 'NODE_ENV';
export const COMPASS_LISTEN_PORT = 'COMPASS_LISTEN_PORT';
export const COMPASS_THROTTLER_TTL = 'COMPASS_THROTTLER_TTL';
export const COMPASS_THROTTLER_LIMIT = 'COMPASS_THROTTLER_LIMIT';
