export enum COMPASS_ENV {
  NODE_ENV = 'NODE_ENV',
  LISTEN_PORT = 'COMPASS_LISTEN_PORT',
  THROTTLER_TTL = 'COMPASS_THROTTLER_TTL',
  THROTTLER_LIMIT = 'COMPASS_THROTTLER_LIMIT',
  MYSQL_DATABASE_URL = 'COMPASS_MYSQL_DATABASE_URL',
  EMAIL_USER = 'COMPASS_EMAIL_USER',
  EMAIL_PASSWORD = 'COMPASS_EMAIL_PASSWORD',
}
